language: node_js
sudo: required
dist: trusty
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
  - '5'
  - '4'
before_script:
  - npm install -g bower polymer-cli
  - bower install
  - npm install -g firebase-tools
script:
  - xvfb-run polymer test
  - polymer build
  - firebase use development
  - firebase deploy --token "1/k6xFwwFt6yDOCyl5kcW-ID_gN7fgf0Td4SajZkFPdTE21TGkXcBsSO4lbv3jIxEy" -m "Auto deployed by Travis"